version: '3.4'

services:
  postgres:
    container_name: threads-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: threads
      POSTGRES_PASSWORD: threads

  backend:
    container_name: threads-backend
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    links:
      - postgres
    restart: always

volumes:
  postgres_data: